from ..database.db import db
from flask_login import UserMixin

class Sticker(db.Model):
    code = db.Column(db.String(10), primary_key=True)
    name = db.Column(db.String(15))
    country = db.Column(db.String(15))
    position = db.Column(db.String(10))

class User(db.Model, UserMixin):
    id = db.Column(db.String(10), primary_key=True, unique=True)
    username = db.Column(db.String(15), unique=True)
    password = db.Column(db.String(20))
    email = db.Column(db.String(30), unique=True)
    location = db.Column(db.String(15))
    cards = db.Column(db.String(1000))
    
# class List(db.Model):
#     user = db.Column(db.String(15), primary_key=True, unique=True)
#     panini = db.Column(db.Integer())

#     fwc1 = db.Column("FWC1", db.Integer())
#     fwc2 = db.Column("FWC2", db.Integer())
#     fwc3 = db.Column("FWC3", db.Integer())
#     fwc4 = db.Column("FWC4", db.Integer())
#     fwc5 = db.Column("FWC5", db.Integer())
#     fwc6 = db.Column("FWC6", db.Integer())
#     fwc7 = db.Column("FWC7", db.Integer())
#     fwc8 = db.Column("FWC8", db.Integer())
#     fwc9 = db.Column("FWC9", db.Integer())
#     fwc10 = db.Column("FWC10", db.Integer())
#     fwc11 = db.Column("FWC11", db.Integer())
#     fwc12 = db.Column("FWC12", db.Integer())
#     fwc13 = db.Column("FWC13", db.Integer())
#     fwc14 = db.Column("FWC14",db.Integer())
#     fwc15 = db.Column("FWC15",db.Integer())
#     fwc16 = db.Column("FWC16",db.Integer())
#     fwc17 = db.Column("FWC17",db.Integer())
#     fwc18 = db.Column("FWC18",db.Integer())
#     fwc19 = db.Column("FWC19",db.Integer())
#     fwc20 = db.Column("FWC20",db.Integer())
#     fwc21 = db.Column("FWC21",db.Integer())
#     fwc22 = db.Column("FWC22",db.Integer())
#     fwc23 = db.Column("FWC23",db.Integer())
#     fwc24 = db.Column("FWC24",db.Integer())
#     fwc25 = db.Column("FWC25",db.Integer())
#     fwc26 = db.Column("FWC26",db.Integer())
#     fwc27 = db.Column("FWC27",db.Integer())
#     fwc28 = db.Column("FWC28",db.Integer())
#     fwc29 = db.Column("FWC29",db.Integer())

#     qat1 = db.Column("QAT1", db.Integer())
#     qat2 = db.Column("QAT2", db.Integer())
#     qat3 = db.Column("QAT3", db.Integer())
#     qat4 = db.Column("QAT4", db.Integer())
#     qat5 = db.Column("QAT5", db.Integer())
#     qat6 = db.Column("QAT6", db.Integer())
#     qat7 = db.Column("QAT7", db.Integer())
#     qat8 = db.Column("QAT8", db.Integer())
#     qat9 = db.Column("QAT9", db.Integer())
#     qat10 = db.Column("QAT10", db.Integer())
#     qat11 = db.Column("QAT11", db.Integer())
#     qat12 = db.Column("QAT12", db.Integer())
#     qat13 = db.Column("QAT13", db.Integer())
#     qat14 = db.Column("QAT14", db.Integer())
#     qat15 = db.Column("QAT15", db.Integer())
#     qat16 = db.Column("QAT16", db.Integer())
#     qat17 = db.Column("QAT17", db.Integer())
#     qat18 = db.Column("QAT18", db.Integer())
#     qat19 = db.Column("QAT19", db.Integer())
#     qat20 = db.Column("QAT20", db.Integer())

#     ecu1 = db.Column("ECU1", db.Integer())
#     ecu2 = db.Column("ECU2", db.Integer())
#     ecu3 = db.Column("ECU3", db.Integer())
#     ecu4 = db.Column("ECU4", db.Integer())
#     ecu5 = db.Column("ECU5", db.Integer())
#     ecu6 = db.Column("ECU6", db.Integer())
#     ecu7 = db.Column("ECU7", db.Integer())
#     ecu8 = db.Column("ECU8", db.Integer())
#     ecu9 = db.Column("ECU9", db.Integer())
#     ecu10 = db.Column("ECU10", db.Integer())
#     ecu11 = db.Column("ECU11", db.Integer())
#     ecu12 = db.Column("ECU12", db.Integer())
#     ecu13 = db.Column("ECU13", db.Integer())
#     ecu14 = db.Column("ECU14", db.Integer())
#     ecu15 = db.Column("ECU15", db.Integer())
#     ecu16 = db.Column("ECU16", db.Integer())
#     ecu17 = db.Column("ECU17", db.Integer())
#     ecu18 = db.Column("ECU18", db.Integer())
#     ecu19 = db.Column("ECU19", db.Integer())
#     ecu20 = db.Column("ECU20", db.Integer())

#     sen1 = db.Column("SEN1", db.Integer())
#     sen2 = db.Column("SEN2", db.Integer())
#     sen3 = db.Column("SEN3", db.Integer())
#     sen4 = db.Column("SEN4", db.Integer())
#     sen5 = db.Column("SEN5", db.Integer())
#     sen6 = db.Column("SEN6", db.Integer())
#     sen7 = db.Column("SEN7", db.Integer())
#     sen8 = db.Column("SEN8", db.Integer())
#     sen9 = db.Column("SEN9", db.Integer())
#     sen10 = db.Column("SEN10", db.Integer())
#     sen11 = db.Column("SEN11", db.Integer())
#     sen12 = db.Column("SEN12", db.Integer())
#     sen13 = db.Column("SEN13", db.Integer())
#     sen14 = db.Column("SEN14", db.Integer())
#     sen15 = db.Column("SEN15", db.Integer())
#     sen16 = db.Column("SEN16", db.Integer())
#     sen17 = db.Column("SEN17", db.Integer())
#     sen18 = db.Column("SEN18", db.Integer())
#     sen19 = db.Column("SEN19", db.Integer())
#     sen20 = db.Column("SEN20", db.Integer())

#     ned1 = db.Column("NED1", db.Integer())
#     ned2 = db.Column("NED2", db.Integer())
#     ned3 = db.Column("NED3", db.Integer())
#     ned4 = db.Column("NED4", db.Integer())
#     ned5 = db.Column("NED5", db.Integer())
#     ned6 = db.Column("NED6", db.Integer())
#     ned7 = db.Column("NED7", db.Integer())
#     ned8 = db.Column("NED8", db.Integer())
#     ned9 = db.Column("NED9", db.Integer())
#     ned10 = db.Column("NED10", db.Integer())
#     ned11 = db.Column("NED11", db.Integer())
#     ned12 = db.Column("NED12", db.Integer())
#     ned13 = db.Column("NED13", db.Integer())
#     ned14 = db.Column("NED14", db.Integer())
#     ned15 = db.Column("NED15", db.Integer())
#     ned16 = db.Column("NED16", db.Integer())
#     ned17 = db.Column("NED17", db.Integer())
#     ned18 = db.Column("NED18", db.Integer())
#     ned19 = db.Column("NED19", db.Integer())
#     ned20 = db.Column("NED20", db.Integer())
